package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка оформления заказа на OZON")
    void generatedTest() {
        step("Открыть 'https://www.ozon.ru/'", () -> {
            step("// todo: just add selenium action");
        });

        step("Выполнить поиск товара \"айфон 13\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Добавить айфон 13 в корзину", () -> {
            step("// todo: just add selenium action");
        });

        step("Перейти в корзину", () -> {
            step("// todo: just add selenium action");
        });

        step("Нажать \"оформить\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Убедиться, что открыта страница оформления заказа содержащая товар \"айфон 13\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.ozon.ru/'", () ->
            open("https://www.ozon.ru/"));

        step("Page title should have text 'Just a moment...'", () -> {
            String expectedTitle = "Just a moment...";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.ozon.ru/'", () ->
            open("https://www.ozon.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}